### ISSUE TITLE
How to differentiate between binary and process query

### ISSUE THREAD

**Issue by andrewgin** [carbonblack/cbfeeds#8]
Hi
I can't seem to find any information about how to differentiate a binary query and a process query.
When I enter a query in Carbon black, whether it is under Process Search and Query Search, the query is the same
eg

    cb.urlver=1&q=firefox.exe&sort=&rows=10&start=0

Is there a field in the IoC structure that defines whether a query is a process query or a binary query?

Thanks

**Comment by jgarman** [comment]
Hi @andrewgin, there are different fields available in a binary query and a process query. Your query doesn't specify any fields, so it's perfectly valid in either context. You can use "firefox.exe" to search for binaries that contain "firefox.exe" in one of its full text fields, or processes that contain "firefox.exe" in its full text index (for example, processes that connected to a hostname "firefox.exe", files that contain the name "firefox.exe", etc.)

If you have more questions drop us a line at dev-support@bit9.com and we can work through your use case. Thanks!
